Poll = read.csv(choose.files())
table(Poll$Smartphone)
summary(Poll$Smartphone)
table(Poll$Sex, Poll$Region)
table(Poll$Region=="Midwest", Poll$State)
table(Poll$State, Poll$Region=="Midwest")
table(Poll$State, Poll$Region=="South")
table(Poll$Internet.Use, Poll$Smartphone)
summary(Poll$Internet.Use)
summary(Poll$Smartphone)
#limited = subset(Poll, Internet.Use == 1 | Smartphone == 1)
summary(limited)
mean(limited$Info.On.Internet)
table(limited$Info.On.Internet)
table(limited$Worry.About.Info)
table(limited$Anonymity.Possible)
table(limited$Tried.Masking.Identity)
table(limited$Privacy.Laws.Effective)
hist(limited$Age)
#max(table(limited$Age, limited$Info.On.Internet))
jitter(c(1, 2, 3))
plot(jitter(limited$Age), jitter(limited$Info.On.Internet))
#tapply(limited$Info.On.Internet, limited$Smartphone, summary)
#tapply(limited$Tried.Masking.Identity, limited$Smartphone, table)